/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
    		auth(controller: "*", action: "*"){
    			before={
    				accessControl{true
    				}
    			}
    		}
			management(controller: "user|role|permission", action: "*"){
				before={
    				accessControl{role("admin")}
    			}
    		}
    		message(controller: "message", action: "delete|update"){
    			before={
    				accessControl{
						permission("message:${actionName}:${params.id}")
    				}
    			}
    		}

    }
}
